### ISSUE TITLE
Feature request `--max-details all`

### ISSUE THREAD

**Issue by thislooksfun** [beuss-git/wpt-results-analyzer#3]
When investigating regressions I usually want to display all the relevant failures, but currently `--max-details` only takes in an int. I can pass a number higher than the amount of errors, like `--max-details 500`, and that works fine, but it would be a little cleaner if there was an option to just list all the details.

**Comment by beuss-git** [comment]
Thanks for the suggestion! I have implemented the `--max-details all` option in da47833f9d9cf33081a39855c7ec474e287d5b24 :^)
